# ==============================================================================
# Prospector Configuration (Lenient)
# ==============================================================================

strictness: medium
test-warnings: false
doc-warnings: false
member-warnings: false

max-line-length: 120

ignore-paths:
  - migrations
  - .pixi
  - .venv
  - __pycache__
  - staticfiles
  - media

pylint:
  run: true
  load-plugins:
    - pylint_django
  options:
    django-settings-module: app.config.entrypoint
  disable:
    - C0111
    - C0114
    - C0115
    - C0116
    - C0103
    - R0903
    - R0801
    - W0212
    - import-outside-toplevel
    - import-error
    - arguments-differ
    - no-member
    - no-else-return
    - unused-import

pyflakes:
  run: true
  disable:
    - F401

pep8:
  run: true
  options:
    max-line-length: 120
  disable:
    - E203
    - E501
    - W503

mccabe:
  run: true
  options:
    max-complexity: 15

dodgy:
  run: true

profile-validator:
  run: false

output-format: grouped